name: Haskell Stack CI

on: [push]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: ulid_stack-work_ubuntu
          restore-keys: ulid_stack-work_ubuntu

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Run test suite including test coverage
        run: stack test --coverage

      - name: Run benchmarks
        run: stack bench

      - name: Build documentation
        run: stack haddock

  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: ulid_stack-work_macos
          restore-keys: ulid_stack-work_macos

      - name: Setup Stack
        uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          stack-no-global: true

      - name: Run test suite including test coverage
        run: stack test --coverage

      - name: Run benchmarks
        run: stack bench

      - name: Build documentation
        run: stack haddock
